apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: User-facing applications
  sourceRepos:
    - 'https://github.com/sojohnnysaid/mirai-app.git'
    - 'https://github.com/sojohnnysaid/static-sites.git'
    - 'https://github.com/sojohnnysaid/sogos-marketing.git'
  destinations:
    - namespace: mirai
      server: https://kubernetes.default.svc
    - namespace: mirai-uat
      server: https://kubernetes.default.svc
    - namespace: redis
      server: https://kubernetes.default.svc
    - namespace: static-sites
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: sogos-marketing
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
