apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- networkpolicy-deny-all.yaml
- networkpolicy-allow-ingress.yaml
- networkpolicy-allow-monitoring.yaml
- networkpolicy-allow-dns.yaml
- networkpolicy-allow-egress-external.yaml
- networkpolicy-allow-intra-namespace.yaml
- resourcequota.yaml
- limitrange.yaml
