apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-namespace.yaml
  - mirai-namespace.yaml
  - redis-namespace.yaml
  - static-sites-namespace.yaml
  - default-namespace.yaml
